spring:
  application:
    name: exclusiveDbLock

  datasource:
    url: jdbc:mariadb://localhost:3306/outbox
    username: root
    password: jottes
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate.ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        jdbc:
          time_zone: UTC
